#!/bin/bash
#
#  noncecashd The noncecash core server.
#
#
# chkconfig: 345 80 20
# description: noncecashd
# processname: noncecashd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/noncecashd, see below
if [ -f /etc/sysconfig/noncecashd ]; then
        . /etc/sysconfig/noncecashd
fi

RETVAL=0

prog=noncecashd
# you can override the lockfile via NONCECASHD_LOCKFILE in /etc/sysconfig/noncecashd
lockfile=${NONCECASHD_LOCKFILE-/var/lock/subsys/noncecashd}

# noncecashd defaults to /usr/bin/noncecashd, override with NONCECASHD_BIN
noncecashd=${NONCECASHD_BIN-/usr/bin/noncecashd}

# noncecashd opts default to -disablewallet, override with NONCECASHD_OPTS
noncecashd_opts=${NONCECASHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $noncecashd $noncecashd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
