#!/bin/bash
#
#  nerocashd The nerocash core server.
#
#
# chkconfig: 345 80 20
# description: nerocashd
# processname: nerocashd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/nerocashd, see below
if [ -f /etc/sysconfig/nerocashd ]; then
        . /etc/sysconfig/nerocashd
fi

RETVAL=0

prog=nerocashd
# you can override the lockfile via NEROCASHD_LOCKFILE in /etc/sysconfig/nerocashd
lockfile=${NEROCASHD_LOCKFILE-/var/lock/subsys/nerocashd}

# nerocashd defaults to /usr/bin/nerocashd, override with NEROCASHD_BIN
nerocashd=${NEROCASHD_BIN-/usr/bin/nerocashd}

# nerocashd opts default to -disablewallet, override with NEROCASHD_OPTS
nerocashd_opts=${NEROCASHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $nerocashd $nerocashd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
