description "Nerocash Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env NEROCASHD_BIN="/usr/bin/nerocashd"
env NEROCASHD_USER="nerocash"
env NEROCASHD_GROUP="nerocash"
env NEROCASHD_PIDDIR="/var/run/nerocashd"
# upstart can't handle variables constructed with other variables
env NEROCASHD_PIDFILE="/var/run/nerocashd/nerocashd.pid"
env NEROCASHD_CONFIGFILE="/etc/nerocash/nerocash.conf"
env NEROCASHD_DATADIR="/var/lib/nerocashd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # nerocashd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$NEROCASHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run nerocashd."
        echo "The setting must appear in $NEROCASHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Nerocash Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$NEROCASHD_PIDDIR"
    chmod 0755 "$NEROCASHD_PIDDIR"
    chown $NEROCASHD_USER:$NEROCASHD_GROUP "$NEROCASHD_PIDDIR"
    chown $NEROCASHD_USER:$NEROCASHD_GROUP "$NEROCASHD_CONFIGFILE"
    chmod 0660 "$NEROCASHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$NEROCASHD_PIDFILE" \
    --chuid $NEROCASHD_USER:$NEROCASHD_GROUP \
    --exec "$NEROCASHD_BIN" \
    -- \
    -pid="$NEROCASHD_PIDFILE" \
    -conf="$NEROCASHD_CONFIGFILE" \
    -datadir="$NEROCASHD_DATADIR" \
    -disablewallet \
    -daemon

